#choosed base image ubuntu
FROM ubuntu:latest

# tags
LABEL purpose="backend"

# change directory
WORKDIR /opt

# adding tomcat into /opt directory # ADD command add form remote location
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.zip /opt

# run some essential command 
RUN apt update && \
apt install unzip openjdk-11-jdk -y && \
unzip apache-tomcat-9.0.93.zip

# adding student war file from remotely to /apache-tomacat.0/webapps
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war  apache-tomcat-9.0.93/webapps/

#adding  mysql connector into /lib
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar apache-tomcat-9.0.93/lib

# copying contex.xml file into apache-tomcat /conf/ 
COPY contex.xml  apache-tomcat-9.0.93/conf/

# adding execuation permissions to catalina.sh file
#RUN chmod +rwx /opt/Apache-tomcat-9.0.93/bin/* .sh  
RUN chmod +rwx /opt/apache-tomcat-9.0.93/bin/*.sh


# exopsing port on 8080
EXPOSE 8080
 
# runnging process
CMD ["/opt/apache-tomcat-9.0.93/bin/catalina.sh", "run"]