#we are placing a base for our docker image
FROM ubuntu:latest
#we are labeling our docker image here
LABEL image="frontendstatic"
#we are running few commands in our container(during container creation)
RUN apt update 
RUN apt install apache2 unzip -y
RUN rm -rf /var/www/html/index.html
#we are copying source code from local storage
COPY index.html * /var/www/html/
#we are moving to /var/www/html
WORKDIR /var/www/html
#we are unzipping and extracting the source code in default deployment enviornment locationx
#we are exposing our container to a port
EXPOSE 80
#we are providing container a processs 
CMD ["apachectl", "-D" ,"FOREGROUND"]










# <!DOCTYPE html>
# <html lang="en">

# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>Traffic Light</title>

#     <!-- Bootstrap CSS -->
#     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

#     <!-- Custom CSS -->
#     <link rel="stylesheet" href="style.css">

#     <!-- jQuery -->
#     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

#     <!-- Popper.js -->
#     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

#     <!-- Bootstrap JS -->
#     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

#     <!-- Custom JavaScript -->
#     <script src="app.js"></script>
# </head>

# <body>
#     <div class="bg-container">
#         <h1 class="heading">Traffic Light</h1>
#         <div class="d-flex flex-row justify-content-between">
#             <div class="d-flex flex-column">
#                 <button id="stopButton" class="button" onclick="onStop()">Stop</button>
#                 <button id="readyButton" class="button" onclick="onReady()">Ready</button>
#                 <button id="goButton" class="button" onclick="onGo()">Go</button>
#             </div>
#             <div>
#                 <div class="boxcontainer">
#                     <div id="stopLight" class="round_circle"></div>
#                     <div id="readyLight" class="round_circle"></div>
#                     <div id="goLight" class="round_circle"></div>
#                 </div>
#             </div>
#         </div>
#     </div>
# </body>

# </html>






# docker install 
# git clone 
# path /
# apt install unzip 
# unzip traffic 
# for rename command mv traffic\ light.html index.html
# mv traffic \ light.css style.css
# mv traffic \ light.js app.js 
# vim index paste ^
# docker build -t app .
# docker images 
# docker run -d -p 80:80 app 
# docker ps 
# hit ip