services:
  nginxfrontendconone:
    build: .
    ports:
      - "81:80"
    network_mode: bridge
    container_name: frontend  # Fixed the spelling of "frontend"
    volumes:
      - myapp:/usr/share/nginx/html/

  nginxfrontendcontwo:
    build: .
    ports: - "32769:80"  # Commented out; if needed, uncomment and adjust
    network_mode: bridge
    volumes:
      - myapp2:/usr/share/nginx/html/
    container_name: frontend2  # Fixed the spelling of "frontend" and updated name

volumes:
  myapp:
  myapp2:

