version: '3.8'  # Specify a version for the Docker Compose file format

services:
  nginxfrontendconone:
    build: .
    ports:
      - "81:81"
    network_mode: bridge
    container_name: frontend  # Fixed the spelling of "frontend"
    volumes:
      - myapp:/usr/share/nginx/html/

  nginxfrontendcontwo:
    build: .
    # ports: - "81:81"  # Commented out; if needed, uncomment and adjust
    network_mode: host
    volumes:
      - myapp2:/usr/share/nginx/html/
    container_name: frontend2  # Fixed the spelling of "frontend" and updated name

volumes:
  myapp:
  myapp2:

networks:
  default:  # Using default network mode; if you need a custom network, adjust here
